

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orcl
spring.datasource.username=system
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true





#batch processing entries
#spring.batch.jdbc.initialize-schema=always
#spring.batch.job.enabled=false
#spring.datasource.url=jdbc:postgresql://localhost:5432/basic
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update

